name: main-actions
run-name: $ {{ github.actor }} is running the main Github Action
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        default: 'nonprod'
        required: true
        type: choice
        options:
        - nonprod
        - staging
        - prod

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: |
          echo "The environment is ${{ inputs.environment }}"
          echo "first-job successful!"
