name: main-actions
run-name: ${{ github.actor }} is running the main Github Action
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        default: nonprod
        required: true
        type: string
        options:
        - nonprod
        - prod

  release:
    types: [published]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT (published-release)
        if: (github.event.release != '' && github.event.release.prerelease == false) || inputs.environment == 'prod'
        run: |
          echo "The environment is PRODUCTION"
          # Print release / tag
          echo ${GITHUB_REF/refs\/tags\//}
          echo "first-job (prod) successful!"
      - name: Print the input name to STDOUT (published-pre-release)
        if: github.event.release.prerelease || inputs.environment == 'nonprod'
        run: |
          echo "The environment is NONPROD"
          # Print release / tag
          echo ${GITHUB_REF/refs\/tags\//}
          echo "first-job (nonprod) successful!"
      - name: Print the input name to STDOUT (manual-workflow-dispatch)
        if: github.event.release == ''
        run: |
          echo "The environment is ${{ inputs.environment }}"
          # Print release / tag
          echo ${GITHUB_REF/refs\/tags\//}
          echo "first-job successful!"

  pre-release-job:
    if: github.event.release.prerelease || inputs.environment == 'nonprod'
    runs-on: ubuntu-latest
    steps:
      - name: Run the job for tags with pre-release published
        run: |
          echo "Running pre-release, this is considered as a nonprod env"
          # Print release / tag
          echo ${GITHUB_REF/refs\/tags\//}
          echo "Pre-release job successful!"
  call-pre-release-job2:
    needs: pre-release-job
    uses: ./.github/workflows/second-actions.yml
    with:
      environment: inputs.environment
      job-one: true
      job-two: false
      job-three: false

  release-job:
    if: github.event.release != '' && github.event.release.prerelease == false
    runs-on: ubuntu-latest
    steps:
      - name: Run the job for tags with release published
        run: |
          echo "Running release, this is considered as a production env"
          # Print release / tag
          echo ${GITHUB_REF/refs\/tags\//}
          echo "Release job successful!"
      
  call-release-job2:
    needs: release-job
    uses: ./.github/workflows/second-actions.yml
    with:
      environment: prod
      job-one: true
      job-two: true
      job-three: true


