name: main-actions
run-name: ${{ github.actor }} is running the main Github Action
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment'
        default: 'nonprod'
        required: true
        type: choice
        options:
        - nonprod
        - staging
        - prod

  release:
    types: [published]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print the input name to STDOUT (published-release)
        if: github.event.release != '' && github.event.release.prerelease == false
        run: |
          echo "The environment is PRODUCTION"
          echo "first-job (prod) successful!"
      - name: Print the input name to STDOUT (published-pre-release)
        if: github.event.release.prerelease
        run: |
          echo "The environment is NONPROD"
          echo "first-job (nonprod) successful!"
      - name: Print the input name to STDOUT (manual-workflow-dispatch)
        if: github.event.release == ''
        run: |
          echo "The environment is ${{ inputs.environment }}"
          echo "first-job successful!"

  pre-release-job:
    if: github.event.release.prerelease
    runs-on: ubuntu-latest
    steps:
      - name: Run the job for tags with pre-release
        run: |
          echo "Running pre-release, this is considered as a nonprod env"
          echo "pre-release job successful!"


